pass name of problem type to error constructor and silence warning
As with similar errors, call the void(String) for NoClassDefFoundError
and VerifyError passing the name of the offending type. If this code
is actually ever executed, this will give us enough information to debug
so we don't need to print a warning message at compile time too.