Allow BooleanType to be extended to both signed/unsigned types
Seeing a lot of errors like:
```
Throwable.java:115: error: Invalid extension of bool to s32
  location: type Throwable
Class.java:3485: error: Invalid extension of bool to s32
    member: method desiredAssertionStatus@ bci 50
  location: type Class
Class.java:3482: error: Invalid extension of bool to s32
    member: method desiredAssertionStatus@ bci 33
  location: type Class
```

due to missing conversions from BooleanType -> other types.

Added BooleanType to the UnsignedIntegerType case as boolean should only
ever be 1 | 0.

Signed-off-by: Dan Heidinga <heidinga@redhat.com>