Initial commit of instanceof-checkcast plugin
The idea is to replace instanceof/checkcast with a call
to a compiled code helper method that implements the semantics
for us.

There will be two versions of the helpers - a fast one and a full one.
The fast one will do the minimal checks that should always be done inline
and the full one will do the slower checks that we don't want at every
callsite.

This commit also includes an example of an instanceof program for testing.

Not yet functional - chasing two major issues:
1) No body included for the fast_instanceof method:
```
error: Function `exact.cc.quarkus.qcc.runtime.main.VMHelpers.fast_instanceof.s32.2.ref.class.java-lang-Object.ref.class.java-lang-Class` has no body
```

2) The LLVMNodeVisitor doesn't know how to lower a TypeLiteral yet

Signed-off-by: Dan Heidinga <heidinga@redhat.com>